server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  directory: ./logs

brpc:
  global:
    naming:
      namingServiceUrl: zookeeper://127.0.0.1:2181/examples
      group: "normal"
      version: 2.0.0
      ignoreFailOfNamingService: false
    client:
      workThreadNum: 1
      ioThreadNum: 1
  custom:
    com.baidu.brpc.example.springboot.api.EchoService:
      naming:
        version: 2.0.0
    com.baidu.brpc.example.springboot.api.AsyncEchoService:
      naming:
        version: 2.0.0